version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=123Qwe123
      - ACCEPT_EULA=Y

  zookeeper:
    image: zookeeper:3.4.13
    network_mode: host
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      - JVM_OPTS=-Xmx2g -XX:+UseG1GC
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=true
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=localhost:2181
      - KAFKA_CREATE_TOPICS=oggtopic:1:1

  oracledb:
    build: Oracle
    ports:
      - 1521:1521
      - 8080:8080
      - 5500:5500
    environment:
      - ORACLE_SID=XE
      - ORACLE_PWD=123Qwe123
    volumes:
      - "oracleData:/opt/oracle/oradata"

  goldengate_oracle:
    build: GoldenGate
    cap_add:
      - SYS_RESOURCE
    volumes:
      - "oracleData:/opt/oracle/oradata"
      - "goldengateDirdat:/u01/app/ogg/dirdat"

  goldengate_bigdata:
    build: GoldenGate-Bigdata
    network_mode: host
    volumes:
      - "goldengateDirdat:/u01/app/ogg/dirdat"


volumes:
  oracleData:
  goldengateDirdat:
